### ISSUE TITLE
still query even when we cannot obtain a signature

### ISSUE THREAD

**Issue by rade** [weaveworks/go-checkpoint#4]
atm, if, for whatever reason, we cannot determine a signature, then we do not perform the remote version check, which seems unnecessarily harsh. I reckon we should just proceed as normal. Perhaps log a warning.

**Comment by rade** [comment]
Looking at the code, the library itself doesn't do any logging - all errors are passed upstream. So by far the easiest thing would be to simply ignore the failed-to-get-signature errors. @tomwilkie what do you reckon?

**Comment by tomwilkie** [comment]
SGTM
